name: build

on: [push]

jobs:
  "build_and_deploy":
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/master'
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
            architecture: 'x64'
        - name: Run Python
          run: "python ./main.py"
        - name: compose zip
          run: "cd BACAP && zip -r ../BACAP.zip * && cd ../"
        - name: deploy file
          uses: wlixcc/SFTP-Deploy-Action@v1.2.1
          with:
            username: ${{ secrets.SSH_USERNAME }}
            server: ${{ secrets.SSH_SERVER }}
            ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
            local_path: './BACAP.zip'
            remote_path: '/var/minecraft/survival/world/datapacks/'
            args: '-o ConnectTimeout=5'
